CREATE TABLE concert (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255),
    description VARCHAR(2000),
    start_time TIMESTAMP(6),
    location VARCHAR(255),
    status VARCHAR(255)
);

CREATE TABLE ticket_category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    price NUMERIC(38, 2),
    capacity INTEGER NOT NULL,
    concert_id BIGINT NOT NULL,

    CONSTRAINT fk_ticket_category_concert
        FOREIGN KEY (concert_id)
        REFERENCES concert(id)
);

CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    concert_id BIGINT NOT NULL,
    customer_email VARCHAR(255) NOT NULL,
    access_token_hash VARCHAR(64) NOT NULL UNIQUE,
    status VARCHAR(255) NOT NULL,
    total_amount NUMERIC(38, 2) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    expires_at TIMESTAMP(6) NOT NULL,
    paid_at TIMESTAMP(6),

    CONSTRAINT fk_orders_concert
        FOREIGN KEY (concert_id)
        REFERENCES concert(id)
);

CREATE TABLE order_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    ticket_category_id BIGINT NOT NULL,
    quantity INTEGER NOT NULL,
    unit_price NUMERIC(38, 2) NOT NULL,

    CONSTRAINT fk_order_item_order
        FOREIGN KEY (order_id)
        REFERENCES orders(id),

    CONSTRAINT fk_order_item_ticket_category
        FOREIGN KEY (ticket_category_id)
        REFERENCES ticket_category(id)
);

CREATE TABLE ticket (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    ticket_category_id BIGINT NOT NULL,
    qr_token VARCHAR(255) NOT NULL UNIQUE,
    status VARCHAR(255) NOT NULL,

    CONSTRAINT fk_ticket_order
        FOREIGN KEY (order_id)
        REFERENCES orders(id),

    CONSTRAINT fk_ticket_ticket_category
        FOREIGN KEY (ticket_category_id)
        REFERENCES ticket_category(id)
);

CREATE INDEX idx_ticket_category_concert_id
    ON ticket_category(concert_id);

CREATE INDEX idx_orders_concert_id
    ON orders(concert_id);

CREATE INDEX idx_order_item_order_id
    ON order_item(order_id);

CREATE INDEX idx_order_item_ticket_category_id
    ON order_item(ticket_category_id);

CREATE INDEX idx_ticket_order_id
    ON ticket(order_id);

CREATE INDEX idx_ticket_ticket_category_id
    ON ticket(ticket_category_id);