CREATE TABLE payment_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id VARCHAR(255) NOT NULL UNIQUE,
    order_id BIGINT NOT NULL,
    payment_status VARCHAR(50) NOT NULL,
    received_at TIMESTAMP(6) NOT NULL,
    processed_at TIMESTAMP(6) NOT NULL,

    CONSTRAINT fk_payment_event_order
        FOREIGN KEY (order_id)
        REFERENCES orders(id)
);

CREATE INDEX idx_payment_event_order_id
    ON payment_event(order_id);