### Variablen
@baseUrl = http://localhost:8080
@concertId = 1
@categoryId = 1
@orderId = 1
@qrToken = DeinToken
@accessToken = ZqKGne3-qcNbg7fdupi-Lm1fm419gCD6HwPELWUSKNk

---Building---
### Konzert als Admin erstellen
POST {{baseUrl}}/api/admin/concerts
Authorization: Basic admin test-password
Content-Type: application/json

{
  "title": "Accordion Symphonic",
  "description": "Von Drachen zu Vulkanausbrüchen - eine musikalische Reise durch die Naturgewalten",
  "startTime": "2027-11-27T16:00:00",
  "location": "Kongresszentrum Heidelberg"
}


### Konzert veröffentlichen
PATCH {{baseUrl}}/api/admin/concerts/{{concertId}}/publish
Authorization: Basic admin test-password


### Ticketkategorie anlegen
POST {{baseUrl}}/api/admin/concerts/{{concertId}}/ticket-categories
Authorization: Basic admin test-password
Content-Type: application/json

{
  "name": "Normal",
  "price": 25.00,
  "capacity": 100
}


### Order erstellen
POST {{baseUrl}}/api/concerts/{{concertId}}/orders
Content-Type: application/json

{
  "customerEmail": "test@example.com",
  "items": [
    {
      "ticketCategoryId": {{categoryId}},
      "quantity": 2
    }
  ]
}


### Eigene Bestellung stornieren
PATCH {{baseUrl}}/api/concerts/{{concertId}}/orders/{{orderId}}/cancel
X-Order-Access-Token: {{accessToken}}