spring.application.name=ticketing

spring.datasource.url=jdbc:postgresql://localhost:5432/ticketing
spring.datasource.username=ticketing
spring.datasource.password=ticketing

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.flyway.enabled=false