### Variablen
@baseUrl = http://localhost:8080
@concertId = 1
@categoryId = 1
@orderId = 6
@qrToken = 797e37a2-530a-4a16-a43d-47d7f11cf1aa

---CONCERTS---
### Alle öffentlichen Konzerte anzeigen
GET {{baseUrl}}/api/concerts


### Konzert als Admin erstellen
POST {{baseUrl}}/api/admin/concerts
Authorization: Basic admin test-password
Content-Type: application/json

{
  "title": "Accordion Symphonic",
  "description": "Von Drachen zu Vulkanausbrüchen - eine musikalische Reise durch die Naturgewalten",
  "startTime": "2027-11-27T16:00:00",
  "location": "Kongresszentrum Heidelberg"
}

### Testkonzert
POST {{baseUrl}}/api/admin/concerts
Authorization: Basic admin test-password
Content-Type: application/json

{
  "title": "Accordion Symphonic 2",
  "description": "Von Drachen zu Vulkanausbrüchen - eine musikalische Reise durch die Naturgewalten",
  "startTime": "2027-11-27T16:00:00",
  "location": "Kongresszentrum Heidelberg"
}


### Alle Konzerte als Admin anzeigen
GET {{baseUrl}}/api/admin/concerts
Authorization: Basic admin test-password


### Konzert veröffentlichen
PATCH {{baseUrl}}/api/admin/concerts/{{concertId}}/publish
Authorization: Basic admin test-password


### Ticketkategorie anlegen
POST {{baseUrl}}/api/admin/concerts/{{concertId}}/ticket-categories
Authorization: Basic admin test-password
Content-Type: application/json

{
  "name": "Normal",
  "price": 30.00,
  "capacity": 1000
}

### Test Ticketkategorie anlegen
POST {{baseUrl}}/api/admin/concerts/{{concertId}}/ticket-categories
Authorization: Basic admin test-password
Content-Type: application/json

{
  "name": "1. Preiskategorie",
  "price": 50.00,
  "capacity": 200
}


### Kategorien mit Verfügbarkeit anzeigen
GET {{baseUrl}}/api/admin/concerts/{{concertId}}/ticket-categories
Authorization: Basic admin test-password


### Order erstellen
POST {{baseUrl}}/api/concerts/{{concertId}}/orders
Content-Type: application/json

{
  "customerEmail": "test@example.com",
  "items": [
    {
      "ticketCategoryId": {{categoryId}},
      "quantity": 2
    }
  ]
}


### Order anzeigen ohne Token
GET {{baseUrl}}/api/concerts/{{concertId}}/orders/{{orderId}}


### Order anzeigen mit falschem Token
GET {{baseUrl}}/api/concerts/{{concertId}}/orders/{{orderId}}
X-Order-Access-Token: ReBSy_2_e9JNHuaoY9jbWVhYSaGgK_geMQ14wfW5XXX


### Order anzeigen mit Token
GET {{baseUrl}}/api/concerts/{{concertId}}/orders/{{orderId}}
X-Order-Access-Token: CJNEPMUJhvZjC_34N0-QrOolkXduv_lSa5EyHRT7py4


### Alle Orders eines Konzerts als Admin anzeigen
GET {{baseUrl}}/api/admin/concerts/{{concertId}}/orders
Authorization: Basic admin test-password


### Eigene Bestellung stornieren
PATCH {{baseUrl}}/api/concerts/{{concertId}}/orders/{{orderId}}/cancel
X-Order-Access-Token:


### Order als bezahlt markieren
PATCH {{baseUrl}}/api/admin/concerts/{{concertId}}/orders/{{orderId}}/paid
Authorization: Basic admin test-password


### Tickets einer Order anzeigen
GET {{baseUrl}}/api/admin/concerts/{{concertId}}/orders/{{orderId}}/tickets
Authorization: Basic admin test-password


### Ticket validieren
GET {{baseUrl}}/api/admin/concerts/{{concertId}}/tickets/validate/{{qrToken}}
Authorization: Basic admin test-password


### Ticket entwerten
PATCH {{baseUrl}}/api/admin/concerts/{{concertId}}/tickets/{{qrToken}}/use
Authorization: Basic admin test-password

### Payment Webhook
POST http://localhost:8080/api/webhooks/payments
Content-Type: application/json
X-Webhook-Signature: d723a9f1151d3805ef0e72667394638abccf7bb3bc3ba1ffb9873cff35a380c0

{"eventId":"evt_mailpit_002","orderId":2,"status":"PAID"}